### ISSUE TITLE
TypeError: Cannot read property '0' of null from title_bar.js

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#126]
When looking through my logs I noticed the following error:
```
[2021-07-14 20:03:23.042] [error] TypeError: Cannot read property '0' of null
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:127:419)
    at Object.remoteMemberFunction (electron/js2c/renderer_init.js:83:2000)
    at HTMLDivElement.<anonymous> (/opt/Thrive Launcher/resources/app.asar/src/title_bar.js:12:59)
```
Would be worth looking into this to see what's up with that.

**Comment by hhyyrylainen** [comment]
Launcher 2.0 uses a completely different framework so this shouldn't be relevant anymore.
