### ISSUE TITLE
Blackscreen on launch in flatpak

### ISSUE THREAD

**Issue by MTRNord** [Revolutionary-Games/Thrive-Launcher#180]
**Describe the bug**
After installing the 2.0.0 launcher via flatpak I cannot launch the launcher.

**To Reproduce**
1. Download via flatpak
2. Run the launcher
3. Get blackscreen

**Expected behavior**
It should work

**Desktop (please complete the following information):**
 - OS: Fedora kinoite  with wayland session
 - Launcher version: 2.0.0

**Additional context**

Log:

```
2022-12-03 16:14:57.4945|INFO|ThriveLauncher.AvaloniaLogger|[Visual] Exception in render loop: 'System.ArgumentException: Invalid create info - no Canvas provided (Parameter 'createInfo')
   at Avalonia.Skia.DrawingContextImpl..ctor(CreateInfo createInfo, IDisposable[] disposables) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 108
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in /_/src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs:line 40
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 618
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 416
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 359
   at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 277
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Visuals/Rendering/RenderLoop.cs:line 162' (RenderLoop #35287174)
```

**Comment by hhyyrylainen** [comment]
Avalonia framework doesn't support wayland. Do you have XWayland installed? I've got plain Fedora 36 workstation and things work fine there.

**Comment by MTRNord** [comment]
> Avalonia framework doesn't support wayland. Do you have XWayland installed? I've got plain Fedora 36 workstation and things work fine there.

yes xwayland is available. I wonder why the flatpak by default then enables wayland :thinking: 

Disabling it with flatseal didnt solve this though

**Comment by hhyyrylainen** [comment]
> yes xwayland is available. I wonder why the flatpak by default then enables wayland thinking

I put it in there so that I wouldn't have to think about it when Avalonia in the far future gets wayland support...

> Disabling it with flatseal didnt solve this though

Presumably you have XWayland installed and working, though? Could you try the standalone Linux build (.7z compressed file) to see if that works? If that doesn't work either (and you have XWayland) then I'd guess the issue is with Avalonia itself. To verify that we'd need another app to test with or you being able to run Thrive Launcher through a .NET debugger to get as much details as possible to open a report to Avalonia. I didn't search yet but it might be possible that there is already an open issue there: https://github.com/AvaloniaUI/Avalonia/issues

Actually I just checked and you might be experiencing this bug: https://github.com/AvaloniaUI/Avalonia/issues/7262

**Comment by MTRNord** [comment]
> Presumably you have XWayland installed and working, though?

Yes thats working :)



> Could you try the standalone Linux build (.7z compressed file) to see if that works?

I will give this a try

> Actually I just checked and you might be experiencing this bug: [AvaloniaUI/Avalonia#7262](https://github.com/AvaloniaUI/Avalonia/issues/7262)

This indeed looks like the same bug I have :+1:

**Comment by MTRNord** [comment]
The standalone version gives me the same error. So I assume it is the bug you linked

**Comment by hhyyrylainen** [comment]
So the situation with this issue is that we'll just need to wait for a fixed Avalonia version and then upgrade to it.

**Comment by hhyyrylainen** [comment]
I'll assume this has gotten fixed by some Avalonia update.
