### ISSUE TITLE
Investigate what can be done with Windows 7 failing to connect to the DevCenter

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#228]
Windows 7 computers (maybe even with latest updates) fail to connect to the DevCenter with this exception:
```
2022-12-08 20:00:04.2520|WARN|LauncherBackend.Services.DevCenterClient|DevCenter status link check failed|System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at LauncherBackend.Services.DevCenterClient.CheckDevCenterConnection()
2022-12-08 20:00:04.2795|DEBUG|LauncherBackend.Services.DevCenterClient|DevCenter request failed with a http exception
2022-12-08 20:00:04.2795|INFO|LauncherBackend.Services.DevCenterClient|We likely couldn't connect to the DevCenter or it is down
2022-12-08 20:00:04.2795|INFO|ThriveLauncher.ViewModels.MainWindowViewModel|DevCenter connection failed
```

Which seems to be caused by Windows 7 not supporting the exactly latest HTTPS connection protocols and ciphers.

Some links that seem to confirm (that one solution is to update to a newer Windows version):
- https://learn.microsoft.com/en-us/answers/questions/764378/authentication-failed-because-the-remote-party-sen.html
- https://stackoverflow.com/questions/66904417/net-core-5-handshakefailure-when-making-https-request
- https://github.com/DevTrevi/DgcReader/issues/89
- https://github.com/robinrodricks/FluentFTP/issues/907

Using ssl checker the dev center server supports the following TLS 1.2 ciphers:
```
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)      
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)             
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)                
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)     
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)            
```

Multiple of which Microsoft list as supported in Windows 7: https://learn.microsoft.com/en-au/windows/win32/secauthn/tls-cipher-suites-in-windows-7

So it should in theory work. Or at least work with latest updates.

There's also this tool: https://www.nartac.com/Products/IISCrypto/Download which might do something

But anyway the end result is that the Launcher might not be able to connect to the DevCenter on Windows 7 (but other features work, likely due to different TLS configuration used by the CDN).

So something should be done to improve things. If latest updates work, that would be great. Or if we can workaround things by specifying the TLS versions to use in the code `SecurityProtocolType` (interestingly the documentation doesn't say which windows version supports TLS 1.3). Specifying 1.2 only might fix things.

**Comment by RacerBG** [comment]
The solution to this problem is the following Windows Update: **KB3042058**

https://support.microsoft.com/en-us/topic/microsoft-security-advisory-update-to-default-cipher-suite-priority-order-may-12-2015-bb018496-3161-2a28-d2e1-7c82cfef7a55

**Comment by hhyyrylainen** [comment]
Nice, that's listed on this Cipher suites page (https://learn.microsoft.com/en-au/windows/win32/secauthn/tls-cipher-suites-in-windows-7) so I guess armed with this knowledge we can help anyone else having the same problem.

**Comment by hhyyrylainen** [comment]
I'll close this issue as there's no reason to keep this open seeing as no one else has ran into this issue so this being open and easier to see probably doesn't help.

**Comment by theunis-allegiance** [comment]
I know this issue is closed, but we can confirm the same is happening on Windows server 2022 Azure Edition. We had to disable quite a lot of Ciphers to get traffic to flow. Weird Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'. issues in dotnet 6.0 running on Service Fabric cluster.
