### ISSUE TITLE
Wine fails to run the Launcher .exe in certain Linux environments

### ISSUE THREAD

**Issue by zevelijah** [Revolutionary-Games/Thrive-Launcher#412]
Please note that you should only report bugs in the **launcher** here. If the launcher has successfully downloaded the game and started it, all problems after that, before the game is closed, are actually problems in the game itself. Those need to be reported to: https://github.com/Revolutionary-Games/Thrive/issues

**Describe the bug**
It failed to launch. According to my logs, this is do to reading protected memory and possibly, by extension, a corruption of memory. 

**To Reproduce**
1. Install .exe on linux
2. Setup using wine
3. Attempt to open thrive launcher
4. It should fail
5. Open logs
6. in the application section, a detail record of actions and exception seen 
**Expected behavior**
It would open window I would configure my download of thrive.

**Screenshots**
I don't have any screenshots per se, but I do have my computer logs referring to the launch (arrows added by me):
06:05:59 systemd: app-gnome-wine\x2dPrograms\x2dThrive\x20Launcher\x2dThrive\x20Launcher-9941.scope: Consumed 2.726s CPU time.
06:05:58 ThriveLauncher.: 0108:err:eventlog:ReportEventW L"Application: ThriveLauncher.exe\nCoreCLR Version: 6.0.1122.52304\n.NET Version: 6.0.11\nDescription: The process was terminated due to an internal error in the .NET Runtime.at IP 0000000140249C64 (0000000140000000) with exit code c0000005.\n"**<----Important?-------------**
06:05:58 ThriveLauncher.: 0108:err:eventlog:ReportEventW L"Application: ThriveLauncher.exe\nCoreCLR Version: 6.0.1122.52304\n.NET Version: 6.0.11\nDescription: The process was terminated due to an internal error in the .NET Runtime.at IP 0000000140249C64 (0000000140000000) with exit code c0000005.\n"
06:05:58 ThriveLauncher.:    at ThriveLauncher.Program.Main(System.String[])
06:05:58 ThriveLauncher.: Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**<----Important?-------------**
06:05:58 ThriveLauncher.:    at ThriveLauncher.Program.Main(String[] args)
06:05:58 ThriveLauncher.:    at ThriveLauncher.Program.InnerMain(String[] args, ServiceProvider services, ILogger programLogger)
06:05:58 ThriveLauncher.:    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 118
06:05:58 ThriveLauncher.:    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 129
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Window.Show() in /_/src/Avalonia.Controls/Window.cs:line 631
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Window.ShowCore(Window parent) in /_/src/Avalonia.Controls/Window.cs:line 693
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 184
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 297
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /_/src/Avalonia.Controls/WindowBase.cs:line 247
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Window.cs:line 916
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 133
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 366
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 39
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 489
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /_/src/Avalonia.Controls/Grid.cs:line 1005
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 1150
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.DockPanel.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/DockPanel.cs:line 112
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Border.cs:line 187
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 39
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/StackPanel.cs:line 207
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 366
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 39
06:05:58 ThriveLauncher.:    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
06:05:58 ThriveLauncher.:    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
06:05:58 ThriveLauncher.:    at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/TextBlock.cs:line 518
06:05:58 ThriveLauncher.:    at Avalonia.Controls.TextBlock.get_TextLayout() in /_/src/Avalonia.Controls/TextBlock.cs:line 166
06:05:58 ThriveLauncher.:    at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text) in /_/src/Avalonia.Controls/TextBlock.cs:line 475
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 71
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 223
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 15
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 280
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 40
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 62
06:05:58 ThriveLauncher.:    at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 129
06:05:58 ThriveLauncher.:    at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 50
06:05:58 ThriveLauncher.:    at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 33
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.5458|FATAL|ThriveLauncher.Program|Unhandled exception in the launcher. PLEASE REPORT THIS TO US!|System.InvalidOperationException: Default font family name can't be null or empty.**<----Important?------------**
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.5088|INFO|ThriveLauncher.Program|Start running Avalonia desktop lifetime
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.4831|INFO|LauncherBackend.Services.LauncherPaths|Temporary folder is: C:\users\nein\Temp\Revolutionary-Games-Launcher
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.4826|INFO|LauncherBackend.Services.LauncherPaths|Default Launcher storage and Thrive version install folder is: C:\users\nein\AppData\Roaming\Thrive-Launcher
06:05:58 ThriveLauncher.: 0120:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems**<----Important?-------------**
06:05:58 ThriveLauncher.: 0120:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution. **<----Important?-------------**
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.3354|INFO|ThriveLauncher.ViewModels.MainWindowViewModel|Fetching Thrive launcher info
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.2778|INFO|ThriveLauncher.AvaloniaLogger|[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #6925935)**<----Important?-------------**
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.0308|INFO|ThriveLauncher.AvaloniaLogger|[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #46496694)
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.0308|INFO|ThriveLauncher.AvaloniaLogger|[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #5166299)
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.0305|INFO|ThriveLauncher.AvaloniaLogger|[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #30400195)
06:05:58 ThriveLauncher.: 2023-11-14 06:05:58.0293|INFO|ThriveLauncher.AvaloniaLogger|[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #25747420)
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.7034|INFO|ThriveLauncher.AvaloniaLogger|LogHost: Initializing to normal mode (.cctor)
06:05:57 ThriveLauncher.:    at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
06:05:57 ThriveLauncher.:    at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
06:05:57 ThriveLauncher.:    at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
06:05:57 ThriveLauncher.:    at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
06:05:57 ThriveLauncher.:    at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)**<----Important?--------**
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.5071|INFO|ThriveLauncher.AvaloniaLogger|[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.3013|INFO|ThriveLauncher.Program|Launcher starting GUI
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.3013|INFO|LauncherBackend.Services.StoreVersionDetector|Not a store version of the launcher
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.3005|INFO|ThriveLauncher.Program|Launcher language (culture) is: en-GB
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.3005|INFO|ThriveLauncher.Program|No language selected, making sure default is applied. Detected default language: en-GB
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.2959|INFO|ThriveLauncher.Services.LoggingManager|Logging level: Info
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.2959|INFO|LauncherBackend.Services.LauncherPaths|Expected old launcher config path is: C:\users\zev-oster\AppData\Roaming\Revolutionary-Games\Launcher
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.2955|INFO|LauncherBackend.Services.LauncherSettingsManager|No existing settings file found, using defaults
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.2949|INFO|LauncherBackend.Services.LauncherPaths|Config folder is: C:\users\nein\AppData\Roaming\Thrive-Launcher
06:05:57 ThriveLauncher.: 2023-11-14 06:05:57.2640|INFO|ThriveLauncher.Program|Thrive Launcher version 2.0.3 starting
06:05:57 ThriveLauncher.: [Information] Default Launcher storage and Thrive version install folder is: C:\users\nein\AppData\Roaming\Thrive-Launcher

It is worse than spaghetti code. I haven't manage to sort through it completely.
**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04 (Lunar Lobster)
 - Launcher version [e.g. 1.2.5]: 2.0.3

**Additional context**
I was having trouble with the linux version, so I tried "wining"(not a word, but it should be) the .exe version. I failed. There seems to be a bunch of unanswered defaults, empty arrays, trouble with the text, all of which may or may not be related to the launcher trying to read protected memory. I will try to get the linux version working, but if you intended for the launcher to work in wine, the know that as far as I have seen, it does not. It could also just be me, but I would be a little suprised.

**Comment by zevelijah** [comment]
Alright, I may simply be crazy then. I fix it on my own time. Shall I close?
